source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0.rc2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0.rc2'

# bourbon mixin lib
gem 'bourbon'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# slim templates
gem 'slim-rails'

# JS libraries
gem 'jquery-rails'
gem 'modernizr-rails'
gem 'selectivizr-rails'
gem 'respond-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use debugger
gem 'debugger', group: [:development, :test]

# validation
gem 'honeypot-captcha'

# deployment etc
gem "mina", github: "nadarei/mina"
gem "astrails-safe", github: "astrails/safe"
gem "whenever", github: "javan/whenever"
gem "bonethug"

# force gems with native extensions to use the versions that have compiled components from the system gems
if RbConfig::CONFIG['target_os'] =~ /mswin|mingw/i

  # rmagick craps out when installed via bundler on windows
  gem 'rmagick', '2.13.2', :path => "C:/Ruby193/lib/ruby/gems/1.9.1/gems/rmagick-2.13.2"
  gem 'mysql2', '0.3.11'

else
  gem 'rmagick', '2.13.2'  
  gem 'mysql2'
end
