source "https://rubygems.org"

gem 'bonethug',      '>=0.0.87'
gem "mina", 		 github: "nadarei/mina"
gem "astrails-safe", github: "astrails/safe"
gem "whenever", 	 github: "javan/whenever"
gem "guard-erb", 	 github: "azt3k/guard-erb"
gem "coffee-script", github: "josh/ruby-coffee-script"
gem "guard-uglify",  github: "customink/guard-uglify"
gem "guard-concat",  github: "mikz/guard-concat"
