source "https://rubygems.org"

gem 'mina',             github: 'nadarei/mina'
gem 'astrails-safe',    github: 'astrails/safe'
gem 'whenever',         github: 'javan/whenever'
gem 'bonethug',         '>=0.0.31'