#!/bin/bash

cd /usr/share && sudo git clone https://github.com/joshdata/mailinabox
sudo bash mailinabox/setup/start.sh

# need to go in and change the default listening ports in /etc/nginx/conf.d/local.conf