#!/bin/bash

# install npm
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install g++ curl libssl-dev apache2-utils git-core
cd ~ && git clone git://github.com/ry/node.git
cd ~/node && ./configure && make && sudo make install

# install bower
sudo npm install bower -g