#!/bin/bash

sudo apt-get install postgresql-9.3 phppgadmin
sudo cp /etc/apache2/conf.d/phppgadmin /etc/apache2/conf-available/phppgadmin.conf
sudo sed -i -e "s/allow from 127.0.0.0\/255.0.0.0 ::1\/128/allow from all/g" /etc/apache2/conf-available/phppgadmin.conf
sudo a2enconf phppgadmin.conf
sudo service apache2 reload